import Head from "next/head";
import Header from "../components/Navbar";
import MainCard from "../components/MainCard";
import SideHeader from "../components/SideHeader";

export default function Home({ latestNews }) {
  const news = latestNews.results;
  const topics = [
    "business",
    "entertainment",
    "environment",
    "food",
    "health",
    "politics",
    "science",
    "sports",
    "technology",
    "top",
    "world",
  ];

  return (
    <div>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex max-w-6xl mx-auto">
        <div className="pt-20 pb-10 flex flex-col border-r pr-12 ">
          {news.map(
            ({ title, description, creator, image_url, keywords, link }) => (
              <MainCard
                title={title}
                description={description}
                creator={creator}
                imgURL={image_url}
                keywords={keywords}
                link={link}
              />
            )
          )}
        </div>
        <div className="pt-20 pb-10 flex flex-col pl-12 w-2/5 max-h-1.5 sticky top-0">
          <SideHeader topics={topics} />
        </div>
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const resLatestNews = await fetch(
    "https://newsdata.io/api/1/news?apikey=pub_29318cd2d47bff58927cc06650faa7501bdd&language=en"
  );
  const latestNews = await resLatestNews.json();
  return {
    props: {
      latestNews,
    },
  };
};
